### ISSUE TITLE
SyntaxError: reserved word "var"

### ISSUE THREAD

**Issue by eimann** [kaneda/hubot-slothme#2]
After installing, it throws this error:

[Fri May 26 2017 18:45:34 GMT+0000 (UTC)] ERROR Unable to load /home/user/myhubot/node_modules/hubot-slothme/src/slothme: SyntaxError: reserved word "var"
  at exports.throwSyntaxError (/home/user/myhubot/node_modules/coffee-script/lib/coffee-script/helpers.js:197:13)
  at Lexer.exports.Lexer.Lexer.error (/home/user/myhubot/node_modules/coffee-script/lib/coffee-script/lexer.js:778:14)
  at Lexer.exports.Lexer.Lexer.identifierToken (/home/user/myhubot/node_modules/coffee-script/lib/coffee-script/lexer.js:102:16)
  at Lexer.exports.Lexer.Lexer.tokenize (/home/user/myhubot/node_modules/coffee-script/lib/coffee-script/lexer.js:30:25)
  at compile (/home/user/myhubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:35:36)
  at Object.loadFile (/home/user/myhubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:176:14)
  at Module.load (/home/user/myhubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Robot.loadFile (/home/user/myhubot/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
  at /home/user/myhubot/node_modules/hubot-slothme/index.coffee:12:11, <js>:26:33
  at FSReqWrap.cb [as oncomplete] (fs.js:260:19)

**Comment by eimann** [comment]
Oh, that was easy, just remove the 'var' and it'll be fine. I'm not doing a PR for that though and just hope that you're making the change. Thank you <3

**Comment by kaneda** [comment]
@eimann I'll fix, ty :)

**Comment by kaneda** [comment]
@eimann fixed in https://github.com/kaneda/hubot-slothme/pull/3
